# Generated by Django 4.2.2 on 2023-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('description', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на facebook аккаунт')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Ссылка на twitter аккаунт')),
                ('pinterest', models.URLField(blank=True, null=True, verbose_name='Ссылка на pinterest аккаунт')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на instagram аккаунт')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайтов',
            },
        ),
    ]
